### ISSUE TITLE
Error when manually searching:  "String cannot be of zero length"

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#1409]
**Description:**

When trying to manually search, occasionally the search will time-out, however in the GUI, it just shows that it's searching but no results are displayed. 

**Radarr Version:**

WIndows 10E
Radarr v. 0.2.0.596 Develop

**Logs:**

```
An error has occurred while trying to parse  (1996): String cannot be of zero length.
Parameter name: oldValue


System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at NzbDrone.Core.Parser.Parser.ParseMovieTitle(String title, Boolean isDir) in C:\projects\radarr-usby1\src\NzbDrone.Core\Parser\Parser.cs:line 406
```

**Comment by galli-leo** [comment]
This is fixed on the latest nightly release.

**Comment by seanvree** [comment]
@galli-leo  - this may be a dumb question, but how do I pull down the nightlies if I'm on windows?

just do a git pull?

**Comment by galli-leo** [comment]
@seanvree Change "Branch" under Settings -> General to "nightly" (without quotes).

**Comment by seanvree** [comment]
@galli-leo  - I'm still unable to manually search.  It just sits there and spins.  I"m on Radarr Ver. 0.2.0.660
nightly

**Comment by galli-leo** [comment]
@seanvree Logs are the same?

**Comment by seanvree** [comment]
@galli-leo  - Looks like there are no errors in the logs.  I'm thinking this MAY be a PHP problem? I think that it actually did parse the results, but it just can't display them for some reason?


```
17-4-21 10:42:42.4|Info|Database|Vacuuming Log database
17-4-21 10:42:42.4|Info|Database|Log database compressed
17-4-21 10:42:49.9|Info|Database|Vacuuming Log database
17-4-21 10:42:49.9|Info|Database|Log database compressed
17-4-21 10:43:13.7|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\1303\banner.jpg not found
17-4-21 10:43:15.5|Info|NzbSearchService|Searching 77 indexers for [Innsaei]
17-4-21 10:45:42.5|Info|DownloadDecisionMaker|Processing 32 releases
17-4-21 10:48:11.3|Info|PreDBService|Starting PreDB Sync
```

**Comment by galli-leo** [comment]
@seanvree Can you set the logs to debug and try searching again? Also did you try incognito mode?

**Comment by seanvree** [comment]
@galli-leo 

https://drive.google.com/file/d/0B7OujkYtbxFNbFVodUJqczE2Y3c/view?usp=sharing

I think it's a PHP thing.  Not sure, just a hunch.

**Comment by galli-leo** [comment]
@seanvree Shouldn't be a php thing, since we are not using php ;). Seems like the actual request goes through fine (/api/release, 200 OK). Can you open the Chrome dev Console, Do a manual search and see if any red error pop up?

**Comment by seanvree** [comment]
@galli-leo  - No errors.

**Comment by galli-leo** [comment]
@seanvree Which movie where you searching for with which indexers? then we might be able to repro it.

**Comment by Blowy111** [comment]
Im getting a very similar error- very odd.
Total coincidence im sure but it started happening right after i updated SABnzbd to the latest version which went 64 bit.
On a manual search, i get the 'connection to backend lost' after about 5 mins and then have to restart Sonarr on the server.
WIll try the nightlies as you suggest and see what happens.

**Comment by seanvree** [comment]
@galli-leo  - 

Okay, for some reason, it started working TODAY....Here's a screenshot:

http://imgur.com/nZlAaMk

I'll monitor some more.  Up to you if you want to close it.

**Comment by galli-leo** [comment]
I will wait a few days. If it doesn't pop up, I will close the issue.

**Comment by seanvree** [comment]
@galli-leo  - 

Hey wanted to update you on this issue - 

So I found out that I cannot see the results on a manual search when accessing the WebUI via my reverse proxy (hostname.com/radarr).  Everything else works just fine in the UI. it IS searching, it just sits there and spins and never shows the results.   

When doing the same search directly:  xx.xx.xx.xx:7878/radarr then I works fine and it displays the results.

See the screenshots below.  The first one is from the same computer, same browser, however, accessing via hostname/radarr
The second one is accessing on the same browser, but directly via IP:port

 http://imgur.com/JUw7IaN

http://imgur.com/OlszNib

Any ideas?

**Comment by galli-leo** [comment]
@seanvree Seems like a caching issues (cache is different for domain and ip address). Can you try both in an incognito window?

**Comment by seanvree** [comment]
@galli-leo  - Nope, same issue.

**Comment by seanvree** [comment]
Hey @galli-leo  - I've been having this issue again.  I'm SURE there is no issue with Radarr, as I THINK it has to do with my reverse proxy settings in IIS.   Do these errors point to anything obvious?

http://imgur.com/cDpGz1N

**Comment by galli-leo** [comment]
@seanvree Seems like an issue with the proxy (502 Badgateway). Can you go to the networking tab and clock on the request that fails?

**Comment by seanvree** [comment]
@galli-leo  - 

I'm not sure I'm following you, but when I'm in the inspect console, NETWORK , and ALL:

I don't see any errors/fails?  It just gets stuck on the poll?Transport , and keeps loading it until I close the page. 

http://i.imgur.com/P9Ba4Xg.png

**Comment by galli-leo** [comment]
@seanvree The poll ones are fine. Did you click search after opening the dev console? Also try putting release in that filter text field, so you only see the search request.

**Comment by seanvree** [comment]
Yes, I clicked search AFTER opening the dev console.  

If I put the relese in the filter I will get no results:

```
[Violation] 'readystatechange' handler took 750ms
SignalRBroadcaster.js:32 SignalR: [connecting]
SignalRBroadcaster.js:32 SignalR: [connected]
jquery.js:9667 [Violation] 'readystatechange' handler took 393ms
jquery.js:4334 [Violation] 'click' handler took 153ms
backbone.signalr.mixin.js:39 updated: [object Object]}
backbone.signalr.mixin.js:15 sync received, re-fetching collection
CommandMessengerItemView.js:43 [netimportsync] Completed
backbone.signalr.mixin.js:39 updated: [object Object]}
4backbone.signalr.mixin.js:15 sync received, re-fetching collection
jquery.js:9664 GET http://seanvree.com/radarr/api/release?movieId=864&sort_by=releaseWeight&order=asc 502 (Bad Gateway)
send @ jquery.js:9664
ajax @ jquery.js:9215
$.ajax @ jquery.ajax.js:21
Backbone.ajax @ backbone.js:1202
Backbone.sync @ backbone.js:1185
sync @ backbone.js:630
sync @ backbone.pageable.js:935
fetch @ backbone.js:860
fetch @ backbone.pageable.js:1227
fetchMovieReleases @ ReleaseCollection.js:84
_searchManual @ MovieSearchLayout.js:59
onShow @ MovieSearchLayout.js:32
triggerMethod @ backbone.marionette.js:524
show @ backbone.marionette.js:878
_showSearch @ MoviesDetailsLayout.js:161
bound @ lodash.underscore.js:665
dispatch @ jquery.js:4670
elemData.handle @ jquery.js:4338
24backbone.signalr.mixin.js:15 sync received, re-fetching collection
```

**Comment by galli-leo** [comment]
@seanvree Are you sure you put the correct name "release" in the filter field? (You have "relese" in your commend :)) If that's the case, can you post the output of accessing http://seanvree.com/radarr/api/release?movieId=864&sort_by=releaseWeight&order=asc&apikey=YOURAPIKEY in your browser?

**Comment by seanvree** [comment]
@galli-leo - HA, Yes, sorry about that. Typo, but yes, it's not finding the movie title in the console when it stalls.  

So, When I go to that link above I have to Auth via IIS, which I do, then it eventually times out with the following IIS error:

HTTP Error 502.3 - Bad Gateway
The operation timed out

So, it IS accessing Radarr...but something is still stalling. 

<blockquote class="imgur-embed-pub" lang="en" data-id="Q3ens25"><a href="//imgur.com/Q3ens25">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
Screenshot:

**Comment by galli-leo** [comment]
@seanvree Btw. I would suggest removing the image, as your api key can be seen.

Anyways, seems like maybe it tries to access the physical path from the webroot? Can you post your reverse proxy settings for Radarr?

**Comment by seanvree** [comment]
@galli-leo   - I think I figured it out!! IT IS PHP!  See my comment here:

https://github.com/causefx/Organizr/issues/390#issuecomment-312423857

**Comment by Blowy111** [comment]
No longer a issue with later versions. Thank you.
