### ISSUE TITLE
Added movies keep getting downloaded

### ISSUE THREAD

**Issue by dYna77** [Radarr/Radarr#1428]
I added my library but now the programm wants to download some of the movies again, although they are recognized as being there.
When i remove them from the queue they keep getting added.
![zwischenablage02](https://cloud.githubusercontent.com/assets/12372255/25303457/a9923f08-2753-11e7-8cd1-62ccaa033b9b.jpg)
![zwischenablage01](https://cloud.githubusercontent.com/assets/12372255/25303458/a9939d8a-2753-11e7-9ac5-9adc06c26e8c.jpg)

**Comment by galli-leo** [comment]
This is because those movies do not meet your cutoff. For example the Cutoff for the default HD Profile is Bluray. Radarr will keep searching & downloading movies that are not yet downloaded in Bluray with that profile. I would set those movies you do not want to be upgraded to unmonitored. This is best done in the Movie Editor.

**Comment by dYna77** [comment]
I changed the profile for every movie in my library to "Any", but they are still getting downloaded; library was updated after that.
![zwischenablage02](https://cloud.githubusercontent.com/assets/12372255/25303690/8c09e2ba-2758-11e7-9a58-736245024461.jpg)
![zwischenablage01](https://cloud.githubusercontent.com/assets/12372255/25303691/8c0c7b56-2758-11e7-96df-57d37c303cbc.jpg)

**Comment by galli-leo** [comment]
Since Any still has a default cutoff of Bluray. Radarr wants to upgrade your HDTVs to Blurays.

**Comment by dYna77** [comment]
Even when set to "unmonitored" they are getting downloaded.

**Comment by galli-leo** [comment]
@dYna77 Have you tried restarting Radarr.

**Comment by dYna77** [comment]
Yes, several times.
But one movie or so pops up in the Queue everytime .

**Comment by kappaknight** [comment]
Yeah, seeing the same bug here. It's wasting a lot of bandwidth and CPU processing the same thing over and over again. Maybe set to check it every few days if it'll keep doing this or set to not download the same crappy version if one already exists?

<img width="767" alt="screenshot 2017-04-25 22 10 21" src="https://cloud.githubusercontent.com/assets/1387666/25415174/076443b2-2a04-11e7-9ded-185c5ad79639.png">

**Comment by galli-leo** [comment]
@kappaknight The problem here is that Radarr parses the movie to be a Remux (e.g. Rings) from the torrent info. But when we actually have downloaded the release, Radarr realizes it's only 720p, hence the cycle. I would advise to blacklist these releases, since they just seem badly labelled. There is not that much we can do, though I am thinking of ways to prevent that.

**Comment by jat80** [comment]
Has this been resolved at all?   Happens ALOT

**Comment by kappaknight** [comment]
No, not that I know of... in looking at my app history, it continues to grab the same files over and over again, even if they really are 1080p.  The parser needs to be updated to recognize what is 1080p, or even what's even wider formats that are better than 1080p. It would also help if you added previously downloaded files to the black list, so it won't grab the exact same file over and over again. By doing the latter, it'll eventually stop this cycle of madness at least, until you fix the former.

**Comment by jat80** [comment]
Just saw it’s downloaded the movie “The Star 2017” via SABNZBD 24 times over night with totalling over 100gb of my data usage. This is a HUGE PROBLEM.

One thing I’ve noticed is if I have more than 10 movies on my list it won’t show the second page in raddar. But when I search for the added movie it comes up. 

Here’s the thing though - All the recent movies added and have been downloaded multiply times were more than the initial 10 hence could not go to the 2nd page to view them without manually searching for them.

**Comment by galli-leo** [comment]
@jat80 @kappaknight Actually, I pushed a commit to develop yesterday that fixes this :)
@jat80 Regarding your issue, try changing the page size under Settings -> Ui -> Page Size

**Comment by jat80** [comment]
@galli-leo my page size was and is still set to 250

**Comment by galli-leo** [comment]
@jat80 The first time you have to change it to something else save and change it to 250 (or whatever) back again.

**Comment by jat80** [comment]
The last update has NOT fixed the issue.  @galli-leo.  Luckily for me I’m Awake this time and it’s only downloaded the movie twice before I’ve stopped it.  This is a huge problem and reluctantly I’m switching back to couch potato.

**Comment by galli-leo** [comment]
@jat80 Do you have an example indexer this keeps happening on? Kinda difficult to reproduce when you only have torrent indexers :/

**Comment by jat80** [comment]
Sorry I should of been more specific with the details.  

I use NZB’s not torrents.

**Comment by jat80** [comment]
Using sabnzbd and nzbplanet

**Comment by galli-leo** [comment]
Yeah I know, that’s why I said I only have torrent indexers. Doesn’t seem to happen with them. Gonna look at them, do you know of any specific movies?

**Comment by jat80** [comment]
Murder on the orient express was the most recent.

**Comment by jat80** [comment]
@galli-leo - I've got screenshots etc for the current movie example if that helps with the problem.  Probably not the best to post them publicly here.  I can DM you on twitter or something?

**Comment by galli-leo** [comment]
Fine to post here by me (lots of others have before) Though release name should be sufficient.

**Comment by davegregoire** [comment]
I'm still experiencing this issue on a regular basis. I am checking the queue and I see repeat downloads all over the place. Its strange though because when I hover over title to see the info, the folder its looking in doesn't exist and I have nothing on my cutoff unmet list.

**Comment by ASAPHAANING** [comment]
Still happens.
