### ISSUE TITLE
No files found are eligible for import in <download_folder>

### ISSUE THREAD

**Issue by jcchristian** [Radarr/Radarr#159]
I downloaded a movie and after it was complete the queue gave me the message "No files found are eligible for import in <download_folder>" and wouldn't rename and move it to my media folder.

Path: ` .../nzbget/downloads/completed/movies/Lost.in.the.Pacific.2016.1080p.WEB-DL.DD5.1.H264-FGT/f4bf01ae551593550d99525268639c7da882eb721c8f0da9236691c88f8a27e2.mkv`

**Comment by onedr0p** [comment]
Obfuscation is a hell of a drug. I don't know how this would be handled TBH.

**Comment by aircave** [comment]
Same issue...
have resorted to using couchpotato force rename check every hour... once renamed, it gets picked up fine.
Maybe it could check for folder name?

**Comment by fryfrog** [comment]
CouchPotato and Sonarr deal with obfuscated file names, it should be solvable. :)

**Comment by jcchristian** [comment]
Just like @fryfrog said. There are tools that deal with obfuscated file names already, so there must be a way. Using the folder name could be a solution. Usually inside the folder there's only the movie file and a NFO. Just filter by file type and/or size to get the movie file.

**Comment by mgladwin** [comment]
Can also use nzb name to help rename obfuscated files? I believe the video sort script works in this way.

**Comment by zerrikan** [comment]
Confirmed getting this as well:
Import failed, path does not exist or is not accessible by Radarr: /downloads/dst/movies/10.Cloverfield.Lane.2016.MULTi.1080p.WEB.H264-SiGeRiS

**Comment by galli-leo** [comment]
Hmm, so one obfuscated file was just imported correctly. I think the problem is in the movie folder parser.

**Comment by Elfman72** [comment]
Seeing the same thing.  DL a folder that had only 1 file in it named xyz.mkv and it is saying there are no video files for import. This is int he activity tab.

The log file states the following(also, this error message is still referring to sonarr, fyi):

`Import failed, path does not exist or is not accessible by Sonarr: /downloads/radarr/NAME OF DL FOLDER RESOLUTION BLAH ENCODED/`

**Comment by galli-leo** [comment]
Can you give us some logs to work with?

**Comment by zerrikan** [comment]
Attached log filed requested.
[radarr.txt](https://github.com/Radarr/Radarr/files/705555/radarr.txt)

**Comment by aschmois** [comment]
I'm currently getting this error for imported movies (just added, did not search). They stay stuck in the activity section and if I remove them they get re-added and the log is filled with these errors. I can't seem to get them to go away, except deleting the movie itself.

The logs only show:

`Import failed, path does not exist or is not accessible by Radarr: PATH_TO_MOVIE`

some are even repeated.

**Comment by galli-leo** [comment]
@aschmois There was a very similar issue here and the solution was to give Radarr root premissions.

**Comment by aschmois** [comment]
I'm currently running it under windows, I have yet to try to give it administrator access, but the error seems to reach further than permissions. I ended up deleting the movies (just on Radarr) to clear up the activity tab. Then just to try it out I added it back and when the sync task occurred the same thing happened. The movie already exists on my drive, all I did was import it into Radarr for informational purposes. I never hit the search button, just hit the add button.

**Comment by zerrikan** [comment]
Update: I think I was able to fix this. I'm using Radarr in an Unraid Docker container along with Nzbget in a docker container as well. I made sure that the /downloads mapping was the exact same for both Radarr and Nzbget and after that I no longer got this error and everything imported ok.

**Comment by jcchristian** [comment]
@zerrikan I already have nzbget and radarr pointing to .../docker/nzbget/downloads!

**Comment by SK360** [comment]
Just to add on to the pile, also had the same issue with an obfuscated file.  Seems to be a lot of them anymore out there.

**Comment by galli-leo** [comment]
This is fixed on the latest release. Please open a new issue if you experience something similar.

**Comment by francesco2013** [comment]
This is NOT fixed I get the same problem and a lot

**Comment by galli-leo** [comment]
@francesco2013 Can you post an example release name / error of this issue? Without that we won't be able to help much.

**Comment by james-fry** [comment]
I'm seeing the same - this is my very 1st download with radarr having just installed today (docker on ubuntu, movies dir is a samba mount)
Message against the item in the activity log is:
_No files found are eligible for import in /mnt/scratch/sabnzbdplus/complete/movies/Rogue One 2016 1080p BluRay x264-SPARKS_

In the dir I have the following files:
htpc@ubuntutv:/mnt/scratch/sabnzbdplus/complete/movies/Rogue One 2016 1080p BluRay x264-SPARKS$ ls -la
total 10336944
drwxr-xr-x 2 htpc htpc        4096 May 19 16:44 .
drwxrwxr-x 4 htpc htpc        4096 May 19 16:52 ..
-rw-r--r-- 1 htpc htpc      247921 Mar 19 15:08 rogue.one.2016.1080p.bluray.x264-sparks.idx
-rw-r--r-- 1 htpc htpc        4265 Mar 19 14:28 rogue.one.2016.1080p.bluray.x264-sparks.jpg
-rw-r--r-- 1 htpc htpc 10565482757 Mar 19 15:10 Rogue.One.2016.1080p.BluRay.x264-SPARKS.mkv
-rw-r--r-- 1 htpc htpc        4313 Mar 19 14:28 rogue.one.2016.1080p.bluray.x264-sparks.nfo
-rw-r--r-- 1 htpc htpc    19267584 Mar 19 15:08 rogue.one.2016.1080p.bluray.x264-sparks.sub

Hope this helps.

**Comment by james-fry** [comment]
Actually radarr did copy the file eventually, but the error message is still shown in the UI

**Comment by galli-leo** [comment]
@james-fry Hmm. Can you make sure the copied file are one and the same? (md5 or something). Also can you go to that movie in Radarr and see if the file shows up under the files tab?

**Comment by james-fry** [comment]
Hi Leo.
I checked and the movie is showing in the movies tab as downloaded - all looks good.
I didnt go as far as using md5, but from file size compare it looks like the files were copied to movies dir correctly + (new) metadata added:
-rwxrwxr-x   1 htpc dialout     2101179 May 19 17:53 Rogue One A Star Wars Story-fanart.jpg
-rwxrwxr-x   1 htpc dialout      247921 Mar 19 15:08 Rogue One A Star Wars Story.idx
-rwxrwxr-x   1 htpc dialout **10565482757** Mar 19 15:10 Rogue One A Star Wars Story.mkv
-rwxrwxr-x   1 htpc dialout       15653 May 19 17:53 Rogue One A Star Wars Story.nfo
-rwxrwxr-x   1 htpc dialout        4313 Mar 19 14:28 Rogue One A Star Wars Story.orig.nfo
-rwxrwxr-x   1 htpc dialout    19267584 Mar 19 15:08 Rogue One A Star Wars Story.sub
-rwxrwxr-x   1 htpc dialout     1347537 May 19 17:53 Rogue One A Star Wars Story.tbn

I'll keep an eye open for this happening again... for now I deleted the message from the queue page (remove from client)

**Comment by mribeiro** [comment]
I'm having this issue today with two movies. Let's use this for the example: going.in.style.2017.multi.1080p.bluray.x264.1-lost-Obfuscated

In the activity tab it says:

> going.in.style.2017.multi.1080p.bluray.x264.1-lost-Obfuscated
> * No files found are eligible for import in /Users/miguel/Downloads/complete/Movies/going.in.style.2017.multi.1080p.bluray.x264.1-lost-Obfuscated/

But inside the folder there's a single mkv file:
```
$ ls /Users/miguel/Downloads/complete/Movies/going.in.style.2017.multi.1080p.bluray.x264.1-lost-Obfuscated/
a377fefbccfb44edb019a6fd1e94afe0.mkv
```

Even when using manual import I see 
> No video files were found in the selected folder.

Any idea?

The other movie/release is The.Mummy.2017.1080p.WEB-DL.H264.AC3-EVO and _lsing_ the folder I have three files:

- The.Mummy.2017.1080p.WEB-DL.H264.AC3-EVO.nfo
- cbcec102521a14a3e67a3ad10b129e59.sfv
- the.mummy.2017.1080p.web-dl.h264.ac3-evo.mkv

This one is not obfuscated though, but still is not being imported.

**Comment by francesco2013** [comment]
Lol I had the same issue with the very same files. I renamed them manually
and uploaded them to Gdrive. Sometimes Radarr does that. Some forms of
obfuscation are not really well supported :)

**Comment by mribeiro** [comment]
How did you rename them @francesco2013 ? Also, The Mummy is not obfuscated. How should I rename it?

**Comment by francesco2013** [comment]
movie_name (year) Bluray-1080p.mkv
movie_name (year) WEB-DL-1080p.mkv 

and so on

**Comment by francesco2013** [comment]
![image](https://user-images.githubusercontent.com/17063002/29069045-8881516a-7c39-11e7-8c58-deffb66fac1c.png)

Exactly the same problem with the same files @mribeiro

**Comment by mribeiro** [comment]
Renamed to `Going in Style (2017) Bluray-1080p.mkv` and also tried `Going in Style (2017).mkv`.
Still says cannot find it.

**Comment by francesco2013** [comment]
Upload it manually man. Use rclone move !

**Comment by adhatcher** [comment]
I am having this issue as well.
