### ISSUE TITLE
[Feature Request] Quick/partial Kodi library update

### ISSUE THREAD

**Issue by beeeeswax** [Radarr/Radarr#2070]
I think Sonarr does this already, and maybe CouchPotato/SickRage but it's been a while since I used those so I may be mixing them up.

I've noticed that when you have the Kodi connection configured to update the library, it performs a full scan.  This is not usually a problem but if 2 or more movies have been thrown into the download queue at once, I find that they complete around the same time.  When the first movie has been copied to it's destination, Radarr kicks off a full scan - so far, so good.  The problem starts when the next completed movie gets copied to it's new home while Kodi is still running that first scan.  I find this often results in that second movie getting missed because Kodi won't listen to the second scan request while it's still busy on the first.  I then have to connect to the server that has Kodi running all the time to handle library updates and do it manually.

Would it be possible to implement a partial/targeted update which only scans in the new folder?  I'm sure CP or Sickrage or both used to do this resulting in library scans only taking seconds and therefore quick enough to handle multiple, tightly bunched update requests.

Radarr Version: 0.2.0.852

I've done some digging and while I couldn't figure out how Sonarr handles this, I think I've found it in SickRage's source: [https://github.com/SickRage/SickRage/blob/72f937b3667166801ff595ea674a7877dd8b67cd/sickbeard/notifiers/kodi.py](url)

Line 490 shows how they target the scan:
`updateCommand = '{{"jsonrpc":"2.0","method":"VideoLibrary.Scan","params":{{"directory":{0}}},"id":1}}'.format((json.dumps(path)))`

I realise they do some magic first to obtain a show name, ID and then path but in Radarr's case, we already know the path to scan because we have to define that when adding the movie don't we?

**Comment by steve1977** [comment]
This would indeed be a great feature. I have a very large library and would avoid scanning the full library every time I add a movie. Also as a result of this, I suffer from the same issue as described above that movies are not being picked up.

Any chance to see this feature being implemented?

**Comment by bobsaggetrfd** [comment]
+1 
Please add this!

**Comment by fhscholl** [comment]
This was fixed in PR #2240. Is it not working?

**Comment by bobsaggetrfd** [comment]
I don't think so. 

I am on the latest version of Radarr as far as I know (0.2.0.902) and when Radarr sends the command to update the Kodi library, it performs a full library update, scanning all movies and tv sources.

**Comment by bobsaggetrfd** [comment]
So I can confirm this works properly in Plex. I don't usually use Plex, but as a test I installed it and then set it up with Radarr to test.
Movie was added instantly to my Plex library.  

It seems the issue is only with Kodi where it performs a full library scan. Hopefully this can be fixed because it would be absolutely awesome.

**Comment by steve1977** [comment]
Facing the same issue with Kodi. Partial update may not be working yet?

**Comment by beeeeswax** [comment]
I'm on v0.2.0.910 and I'm still seeing full library scans in Kodi.  Is there a new setting somewhere for this?  I don't see anything in [Connections] -> [Kodi] for it.

**Comment by bobsaggetrfd** [comment]
I don't believe it's been fixed yet. 
I have been checking every other day hoping it will be.

**Comment by Qstick** [comment]
This works as expected for me

- Radarr sends request to Kodi to get movies
  - `http://localhost:8080/jsonrpc?request={"jsonrpc": "2.0", "id": 10, "method": "VideoLibrary.GetMovies", "params":{"properties":["file","imdbnumber"]}}`
- Radarr cycles thru movies and matches up imdb
- Radarr uses matched path to selectively update library

Logs:

![image](https://user-images.githubusercontent.com/376117/35604375-02696336-0610-11e8-8264-2a5713d50455.png)

**Comment by bobsaggetrfd** [comment]
I just tested it again after reading your post and it's still performing a full library scan (both movies and then TV shows) when adding the movie to Kodi.

**Comment by Qstick** [comment]
Yep, that's going to happen with a movie add. As mentioned above when you are adding a movie there is not already a entry in Kodi, thus Radarr is not going to be able to find it and selectivity update the path as it does with a TV show when we get a new episode. I think best case will be update the entire movie library by calling a `Files.GetSources` api call to Kodi, but its still going to take some time vs. what you see when Sonarr and SickRage update Kodi because they can update a select TV show path. Since the movie is not already in Kodi Radarr must revert back to updating the library to find the new movie path.

**Comment by Qstick** [comment]
There may be another way about this, I'll throw some code around tomorrow and see what I can do.

**Comment by bobsaggetrfd** [comment]
> There may be another way about this, I'll throw some code around tomorrow and see what I can do.

Thanks so much. Anything you can do to help with this would be greatly appreciated.

**Comment by CorentinB** [comment]
Looks like this is still an issue 2 years later.. :(
@Qstick did you ever experiment a bit with a workaround, or are you aware of one?

**Comment by hugepants** [comment]
@CorentinB A simple workaround would be to use a [custom script](https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts) to update the library instead.

Using [texturecache.py](https://github.com/MilhouseVH/texturecache.py) will solve the issue in two ways:
1) Scan only the base movie directory which avoids tv shows and results in a faster scan.
2) Wait until the scan is complete before passing control back to Radarr.

In the custom script parameters, enter something like this: `vscan /storage/movies` where the path is your base movie directory.
