### ISSUE TITLE
File or Folder naming with A,An or The at end

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#3201]
I want file and folder name with period instead of space so I tried {Movie.TitleThe} but it give name as `Movie.Title.,The` it should be  `Movie.Title,The` .

[AB#873](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/873)

**Comment by Qstick** [comment]
This is fixed in referenced PR

**Comment by SJ50** [comment]
@Qstick is it possible to test this fix?

**Comment by Qstick** [comment]
It should be in the latest build, it was fixed awhile back

**Comment by SJ50** [comment]
@Qstick no it is not, I have just downloaded nightly build and fix is not there as well.
If you see PR it shows "fix-titlethe-seperators" branch force pushed and it got deleted without merge.

This what shows in develop build (0.2.0.1450).

![image](https://user-images.githubusercontent.com/4822384/72763438-e4efa580-3c37-11ea-8123-3f931169b63a.png)

**Comment by SJ50** [comment]
@Qstick any update?

**Comment by Qstick** [comment]
Merged in Aphrodite last night

**Comment by SJ50** [comment]
@Qstick I just tested with Version 3.0.0.2998 (Package Version aphrodite-77dd8ca-921 by hotio ) but renamer still show  `Title.,The`  instead `Title,The`
Am I using wrong version?

![image](https://user-images.githubusercontent.com/4822384/82855213-04803d00-9f4e-11ea-87be-61542157479d.png)

![image](https://user-images.githubusercontent.com/4822384/82855378-7eb0c180-9f4e-11ea-844d-e033203b9e4c.png)

![image](https://user-images.githubusercontent.com/4822384/82855426-9e47ea00-9f4e-11ea-940a-ad290b467a5b.png)

**Comment by SJ50** [comment]
@Qstick how to test the fix?

**Comment by SJ50** [comment]
@Qstick This is not fixed, please reopen.

**Comment by SJ50** [comment]
Please reopen this issue, this is not fixed.

**Comment by bakerboy448** [comment]
@SJ50 can you grab a quick tracelog of an attempted rename.

I hopefully don't think we'll need it, but it's always good to have! if it is something easy to grab.

**Comment by SJ50** [comment]
@bakerboy448 here is tracer log https://pastebin.com/7aX4VV2m

**Comment by SJ50** [comment]
@bakerboy448 another one where file name has "." before The. https://pastebin.com/D686dru8
