### ISSUE TITLE
Imported Movies from Disk Identify as Wrong Quality

### ISSUE THREAD

**Issue by julestop** [Radarr/Radarr#380]
I imported some of my existing movies from disk, and they show as the wrong quality... I think the issue may be that they don't have their qualities in their names, so may be difficult to identify them...
For example, 'American Sniper' should be 1080P Bluray, but showing as HDTV-1080P.

![screen shot 2017-01-22 at 7 55 39 am](https://cloud.githubusercontent.com/assets/1585230/22182636/34f1ea44-e078-11e6-9838-408c74d10163.png)
![screen shot 2017-01-22 at 7 55 23 am](https://cloud.githubusercontent.com/assets/1585230/22182637/3675c9f8-e078-11e6-8172-c6996ffd3e6b.png)

**Comment by morpheus2n2** [comment]
Have you changed the labeling for the qualities under settings, as it will label it as HDTV if you still have the default labels.

**Comment by julestop** [comment]
I haven't changed the defaults... 
![screen shot 2017-01-22 at 10 01 55 am](https://cloud.githubusercontent.com/assets/1585230/22183342/f135c0d4-e089-11e6-8d0b-db148aad4d9e.png)

but the weird thing is that the newly downloaded movies identify properly as Bluray, just the imported files are wrongly identified.

**Comment by morpheus2n2** [comment]
That may be the problem, and its the Profiles page you need to change the labels not quality

**Comment by galli-leo** [comment]
@morpheus2n2 @julestop No, that's not what's happening. I designed the import existing movies to use MediaInfo to guess the quality, if it cannot figure it out according to the filename. So it knows it's 1080p and then uses the size to determine the Quality (According to your profiles). It is probably right under the size required to be a Bluray.

**Comment by morpheus2n2** [comment]
@galli-leo ahh awesome that explains it thank you :)

**Comment by julestop** [comment]
@galli-leo Righton, Thanks for the info

**Comment by hotio** [comment]
Your file size of 12.2GB probably matches with HDTV and Bluray, from the picture posted:
Bluray: unlimited
HDTV: 13.67GB

Just use the proper tag in your filenames, you want have those problems....It's still software, not magic.
Me personally also have a very hard time guessing somebody's age from the back of their shoes.

**Comment by julestop** [comment]
I'm still having issues, even after lowering the quality for HDTV-1080P It's still identifying as such. I deleted the movie and re-added it.
Not sure what to do...
![screen shot 2017-01-22 at 9 13 40 pm](https://cloud.githubusercontent.com/assets/1585230/22189018/cff720c6-e0e7-11e6-96a9-2b00db12e8a4.png)

**Comment by hotio** [comment]
Add `Bluray` to your filename

**Comment by SupFrost** [comment]
I added a 4K movie which I already had (Deadpool) and Radarr is mislabeling them.
![image](https://cloud.githubusercontent.com/assets/7328317/22201521/44542e10-e164-11e6-973a-d656dac85b7a.png)

Quality Definitions
![image](https://cloud.githubusercontent.com/assets/7328317/22201542/5bf8e57e-e164-11e6-8f2d-e6ebf4bb0af7.png)
![image](https://cloud.githubusercontent.com/assets/7328317/22201566/6f06daea-e164-11e6-9ce0-b1a78d214e52.png)

**Comment by julestop** [comment]
The problem is I have 500+ Movies... 99% are 1080P Bluray

**Comment by hotio** [comment]
Than quickly rename them to include Bluray-1080p in the filename, problem solved in about 5 minutes.

**Comment by hotio** [comment]
On windows use Advanced Renamer https://www.advancedrenamer.com

**Comment by galli-leo** [comment]
The quality of existing files can now be changed in the details page on the latest nightly release.

**Comment by imperativeoz** [comment]
Thanks so much @galli-leo and everyone. Any chance the following can be added to the "Movies" window:
1- file size - can be added as part of the details of local files without having to go into details of specific movies.
2- ability to search by file size range from the main "Movies" window.
3- option to change the the local movie quality from "selected files"

I have the same issue above and will be impossible to change quality of existing files in the details of each movies. I have 4,000+ movies and 80% of them seem mislabeled.

Thanks in Advance!

**Comment by stefer09** [comment]
+1 on this, I have the same issues, lots of movies!  Changing the profile sizes for HDTV didn't fix it, nor renaming them with Bluray-1080p or Bluray in the title.  Thanks!
