### ISSUE TITLE
aprodite: After upgrade from develop branch profiles have duplicates

### ISSUE THREAD

**Issue by arpitgupta** [Radarr/Radarr#3857]
I just upgraded to aphrodite release and i noticed that my existing qualities now had duplicates. I had already selected WEBDL-1080 so that was selected as well as grouped quality which had both WEBDL and WEBRIP. Any time i tried to update the profile i would get error saying

```
Invalid request Validation failed: 
 -- Items: Qualities can only be used once
```

Same was seen for multiple profiles.

I got around this by creating new profiles and updating all movies to the new profile and then deleting the old ones. So pretty easy to get around this. Looks like Sonarr v3 does not do this explicit validation as i had the same happen there but i was still able to update all the profiles.

Version
2.0.0.2143
.NET Core
Yes
Docker
Yes
DB Migration
159

**Comment by Qstick** [comment]
This was fixed, 2143 had a bad migration

**Comment by dm3ch** [comment]
Just found that may be the same on my installation:
```
Version
2.0.0.2185
.NET Core
Yes
Docker
Yes
DB Migration
160
```

**Comment by Qstick** [comment]
You'll need to delete the profile in question and remake it, you were likely hit with the bad migration before it was fixed

**Comment by dm3ch** [comment]
@Qstick But suddenly I can't remove profile - delete button don't work. :|

**Comment by dannymichel** [comment]
Same goes for me, I can't delete the profile and am having the ``Qualities can only be used once`` issue

**Comment by wessel145** [comment]
Same, can't edit profiles

docker on latest linuxserver/radarr:preview

**Comment by dannymichel** [comment]
I just deleted every single profile i have and im still having this issue.
