### ISSUE TITLE
Movie release doesn't show up in the the Activity Queue?

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#3858]
There are times where you go to download something and Radarr cannot track the download. Please post the Movie and the Release name here. Maybe it's something we can work into the Parser.

This is a possible duplicate of https://github.com/Radarr/Radarr/issues/3085 but I want to moderate this issue instead.

Movie: Taken 2
Release Name: Taken.2.UNCUT.EXTENDED.2012.1080p.BluRay.DTS.x264-DON

**Comment by Qstick** [comment]
This maybe fixed now to where they actually show (even when not parsable)

**Comment by onedr0p** [comment]
Cool, I'll close it. :)

**Comment by Qstick** [comment]
Well I'm not for certain, but maybe worth a test if you have an example

**Comment by onedr0p** [comment]
It's been awhile since I noticed this behavior myself. I'll post an update if I see it happen.

**Comment by Ed-Savill** [comment]
Hey, I am still having this issue with about 100 movies. How would you like the titles as it's a huge amount of them?

**Comment by Krandor1** [comment]
What version are you running?

**Comment by Ed-Savill** [comment]
v0.2.0.1504
