### ISSUE TITLE
Existing titles have blank title after restart

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#3958]
After restarting radarr some titles are blank. When I click edit I can see which movie it should be by checking the path.

- Radarr-version: 0.2.0.1450 - 03 Dec 2019
 - OS: Synology
 - Browser and Version: chrome 79

![2019-12-17 10_30_01-Movies - Radarr](https://user-images.githubusercontent.com/671621/70983171-8d9a6a80-20b8-11ea-832d-581f5288a127.png)

**Comment by B-Mqn** [comment]
I'm having the same issue.
Only started happening recently with no changes to the system.
Mine is missing from the wanted files but may be from existing downloaded ones too, I don't look there.
The other issue following from this is with no title it doesn't find anything in search when looking to download.
I deleted all 3 and re added and 1 got a title but other two stayed titleless.

Radarr Ver. 0.2.0.1450
Windows 7 64 bit Running as service
Chrome Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by modparts** [comment]
I have the same problem since this morning

**Comment by ohhell6969** [comment]
same

**Comment by jwiese997** [comment]
same

**Comment by doczong** [comment]
Same.

**Comment by Ruta25** [comment]
Same here

**Comment by mazafra1** [comment]
tmdb api is down! It's not radarr

**Comment by doczong** [comment]
Well, it is radarr.  For an external API to go down, to clear out a local data asset, there needs to be some kind of sanity or bug check involved on refresh before wiping out the local asset.

**Comment by mazafra1** [comment]
> Well, it is radarr. For an external API to go down, to clear out a local data asset, there needs to be some kind of sanity or bug check involved on refresh before wiping out the local asset.

The API is not down, but it's returning blank titles! Please, read the link I posted.

Sorry if I caused a misunderstanding.

**Comment by Foxbond** [comment]
> No, it's not radarr. Tmdb API is not down, but it's returning blank titles! Please, read the link I posted.


Some validation should happen on Radarr side, at least "len < 2"

Related issue: #3957

**Comment by mazafra1** [comment]
> > No, it's not radarr. Tmdb API is not down, but it's returning blank titles! Please, read the link I posted.
> 
> Some validation should happen on Radarr side, at least "len < 2"
> 
> Related issue: #3957

Yes, something like that could be put in place, though with challenges.

Some short movie titles:
    “If…”, de Lindsay Anderson.
    “Pi”, de Darren Arofnosky.
    “Up”, de Pete Docter y Bob Peterson.
    “300”, de Zack Snyder.
    “Z”, de Costa Gavras.
    “It”, de Tommy Lee Wallace.
    “Them”, de Gordon Douglas.
    “Q”, de Laurent Bouhnik.
    “Duel”, de Steven Spielberg.
    “Once”, de John Carney.

**Comment by beeeeswax** [comment]
Is there any workaround for this?  I suddenly have a load of title-less movies and I can't seem to do anything with them.  Knowing what they are, searching for them brings back no results. If I go to the Movie Editor, I can't edit them or remove them from the database.

The only way I can even get Radarr to recognise they exist is by trying to add them as new movies - then is gives me the "Already exists" button but when I click this, I get a 404.  Help!

**Comment by Qstick** [comment]
Everything should be fixed on TMDb side, we will add some title validation to ensure movies arnt refreshed if critical data is blank

**Comment by beeeeswax** [comment]
I've managed to rescue the 20 or so movies that had gone blank but it took some messing around.  In the main Movies list, sorted by title, they were all showing at the top of the list.  Refreshing them wasn't doing anything but after attempting a refresh, if I edited them, changed the availability, saved, changed the availability back to its original value and finally saved again, the proper data pops back in.  Weird.

**Comment by deusxanime** [comment]
Had the same issue, but working for me now just to hit the refresh icon and it is pulling down titles, etc. again.

**Comment by aterriblegamer** [comment]
My movie list is fine, its my Wanted list that is still broken. Is there a way to fix that?

**Comment by doczong** [comment]
Issued a manual refresh - Some titles pulled down in my "Monitored Only" list, some did not.  In fact, Radarr is now showing many unmonitored movies in the montiroed only list, even though they are "Downloaded" in grey (not green). 

Which is odd.  Might be reflective of a symptom of this, or might be a new issue because of this.

**Comment by vcantrell** [comment]
Just saying but this issue isn't resolved. My Radarr still messes up new movies every night during scheduled tasks. Assuming there's still issues with TMDb pulls and that causes it to lose the name for random new movies nightly, which then renames the folder to blank (year) and causes Plex to lose the match because it shows the title as *yearbreak* - Running 0.2.0.1450 and tried refreshing titles with missing names with no success.

**Comment by pven** [comment]
Works ok here. When I refresh a empty title it is filled.
