### ISSUE TITLE
Manually searching an indexer gives ID does not match a known language and Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Flupster** [Radarr/Radarr#4376]
Searching an indexer sometimes results in two errors

```
[v3.0.0.2892] System.ArgumentException: ID does not match a known language
Parameter name: id
  at NzbDrone.Core.Languages.Language.FindById (System.Int32 id) [0x0003b] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at NzbDrone.Core.Languages.Language.op_Explicit (System.Int32 id) [0x00000] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at NzbDrone.Core.Parser.Augmenters.AugmentWithReleaseInfo.AugmentMovieInfo (NzbDrone.Core.Parser.Model.ParsedMovieInfo movieInfo, System.Object helper) [0x000ba] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at NzbDrone.Core.Parser.ParsingService.AugmentMovieInfo (NzbDrone.Core.Parser.Model.ParsedMovieInfo minimalInfo, System.Collections.Generic.List`1[T] helpers) [0x0005e] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at NzbDrone.Core.Parser.ParsingService.EnhanceMovieInfo (NzbDrone.Core.Parser.Model.ParsedMovieInfo minimalInfo, System.Collections.Generic.List`1[T] helpers) [0x00003] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo (System.String title, System.Collections.Generic.List`1[T] helpers) [0x0001b] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker+<GetDecisions>d__8.MoveNext () [0x000ff] in <019dcef95bb34ce58e3e25a1f709d289>:0
```

followed by  

```
2020-4-29 23:13:27.4|Error|ReleaseModule|Movie search failed: Object reference not set to an instance of an object

[v3.0.0.2892] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.DecisionEngine.DownloadDecisionPriorizationService+<>c.<PrioritizeDecisionsForMovies>b__4_1 (NzbDrone.Core.DecisionEngine.DownloadDecision c) [0x0000b] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at System.Linq.Lookup`2[TKey,TElement].Create (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0001a] in <d22af090bceb4be792f53595cf074724>:0
  at System.Linq.GroupedResultEnumerable`3[TSource,TKey,TResult].GetEnumerator () [0x00000] in <d22af090bceb4be792f53595cf074724>:0
  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00021] in <d22af090bceb4be792f53595cf074724>:0
  at System.Linq.Set`1[TElement].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) [0x0001b] in <d22af090bceb4be792f53595cf074724>:0
  at System.Linq.Enumerable+UnionIterator`1[TSource].FillSet () [0x00023] in <d22af090bceb4be792f53595cf074724>:0
  at System.Linq.Enumerable+UnionIterator`1[TSource].ToList () [0x00000] in <d22af090bceb4be792f53595cf074724>:0
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in <d22af090bceb4be792f53595cf074724>:0
  at NzbDrone.Core.DecisionEngine.DownloadDecisionPriorizationService.PrioritizeDecisionsForMovies (System.Collections.Generic.List`1[T] decisions) [0x000a3] in <019dcef95bb34ce58e3e25a1f709d289>:0
  at Radarr.Api.V3.Indexers.ReleaseModule.GetMovieReleases (System.Int32 movieId) [0x0000f] in <b6ea5404c5b04d28971f796862dd8482>:0
```

This is on latest aphrodite branch, mono version is 6.8.0.105, OS is ubuntu 20.04, indexer is jackett through torznab indexer

**Comment by Flupster** [comment]
Supplying a trace route to help diagnose issue

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/4567664/radarr.trace.txt)

**Comment by Flupster** [comment]
I resolved the issue by removing all the databases and reimporting, It would appear upgrading from Radarr 2->3 caused some issues

**Comment by bakerboy448** [comment]
@Qstick I think we can close this given we haven't heard of any repeat issues? Or were you going to work on the migration?

**Comment by simonk83** [comment]
I’m also having this issue...

**Comment by bakerboy448** [comment]
@simonk83 version? snippet of the trace log of the issue?

**Comment by simonk83** [comment]
Sure:

`2020-12-31 15:42:41.4|Error|DownloadDecisionMaker|Couldn't process release.

[v3.0.1.4259] System.ArgumentException: ID does not match a known language (Parameter 'id')
   at NzbDrone.Core.Languages.Language.FindById(Int32 id) in D:\a\1\s\src\NzbDrone.Core\Languages\Language.cs:line 159
   at NzbDrone.Core.Parser.Augmenters.AugmentWithReleaseInfo.AugmentMovieInfo(ParsedMovieInfo movieInfo, Object helper) in D:\a\1\s\src\NzbDrone.Core\Parser\Augmenters\AugmentWithReleaseInfo.cs:line 46
   at NzbDrone.Core.Parser.ParsingService.EnhanceMovieInfo(ParsedMovieInfo minimalInfo, List`1 helpers) in D:\a\1\s\src\NzbDrone.Core\Parser\ParsingService.cs:line 74
   at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo(String title, List`1 helpers) in D:\a\1\s\src\NzbDrone.Core\Parser\ParsingService.cs:line 63
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.GetDecisions(List`1 reports, SearchCriteriaBase searchCriteria)+MoveNext() in D:\a\1\s\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 76


2020-12-31 15:42:41.4|Error|DownloadDecisionMaker|Couldn't process release.

[v3.0.1.4259] System.ArgumentException: ID does not match a known language (Parameter 'id')
   at NzbDrone.Core.Languages.Language.FindById(Int32 id) in D:\a\1\s\src\NzbDrone.Core\Languages\Language.cs:line 159
   at NzbDrone.Core.Parser.Augmenters.AugmentWithReleaseInfo.AugmentMovieInfo(ParsedMovieInfo movieInfo, Object helper) in D:\a\1\s\src\NzbDrone.Core\Parser\Augmenters\AugmentWithReleaseInfo.cs:line 46
   at NzbDrone.Core.Parser.ParsingService.EnhanceMovieInfo(ParsedMovieInfo minimalInfo, List`1 helpers) in D:\a\1\s\src\NzbDrone.Core\Parser\ParsingService.cs:line 74
   at NzbDrone.Core.Parser.ParsingService.ParseMovieInfo(String title, List`1 helpers) in D:\a\1\s\src\NzbDrone.Core\Parser\ParsingService.cs:line 63
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.GetDecisions(List`1 reports, SearchCriteriaBase searchCriteria)+MoveNext() in D:\a\1\s\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 76 `

Yell out if you need the full log or anything else

**Comment by simonk83** [comment]
This was manually (interactive) searching for a movie that is definitely present on an indexer. The ui just returns no results, but the logs are as above

**Comment by bakerboy448** [comment]
@simonk83 

sounds like you did what you’re explicitly told not to

https://wiki.servarr.com/Radarr_FAQ#can_i_switch_between_branches

>Check with the development team to see if you can switch from nightly to master; nightly to develop; or develop to master for your given build.

Go back to nightly until the next stable release

anyway....closing, since the original issue appears to have been resolved

**Comment by simonk83** [comment]
Hmm. I mean I only did that because there was a sticky in the subreddit saying to do it...

**Comment by bakerboy448** [comment]
@simonk83 

you installed “3.0.1.4259”

that comment states

“ For builds Nightly 3.0.0.4203 and master/develop 3.0.0.4204, yes.

But this may not always be the case”

**Comment by simonk83** [comment]
I'm on 4259 now, but I wasn't when I upgraded.

Regardless, I've reverted back to an old backup (from before I tried Master) and it's still occurring so as the guy above said, perhaps this happened during the migration from v2 to v3.

As far as I can tell it only happens to moves that are part of a "collection" (I'm using LoTR at the moment, but I tested with some random standalone movies and results came through fine, whereas other movies that are part of a collection (Aliens for example) all give this error).
