### ISSUE TITLE
Completed Download Handling

### ISSUE THREAD

**Issue by shocker2** [Radarr/Radarr#658]
Hello,
   When some movies are downloaded from NZB the filename is not getting renamed correctly.
For example in Sonarr if I have the complete download handling enabled, and in Media Management the Rename Episodes disabled, everything is handled correctly, the episode name gets the release name.
   I've tested this in Radarr with the same settings, in Media Management the Rename Movies is disabled and in Download Client everything is enabled. Sometimes when a Movie is getting downloaded I have this structure: /path/to/Movie (Year)/534sdfjkasdklf45423434.mkv. The movie filename is not getting the release name.
  Also I've seen that there were some discussions regarding the movie name, is it possible to have the movie name as the release version? For example: /path/to/The.Movie.Title.1080p.BluRay-RLS/The.Movie.Title.1080p.BluRay-RLS.mkv ?

Thanks and keep up the good work !  :)

**Comment by galli-leo** [comment]
Well if you disable rename movie, we won't to any renaming :). If you want to rename it to the Nzb name, try enabling rename movie, show advanced settings and change the format to {Original Title}.

**Comment by shocker2** [comment]
Thanks for the feedback. I tough that it's the same as Sonarr :)
I'll try with this option then. Thank you!

**Comment by shocker2** [comment]
The issue is the same even when I enable the movie rename: The Movie Name (2015)/0ca80bc8aa8e4d40b74b8dbde168be9f.mkv

**Comment by shocker2** [comment]
@galli-leo can you please have a look on this one?

**Comment by onedr0p** [comment]
Does the folder get named correctly? Did you try using {Movie Title} in the filename?

**Comment by onedr0p** [comment]
Never mind, you want the release title to be the filename..

**Comment by shocker2** [comment]
The folder it's ok. The file is not getting renamed with the release name.

**Comment by onedr0p** [comment]
@galli-leo maybe we should rename original title to release title.

**Comment by shocker2** [comment]
I've been using Sonarr for two years now, and with the file renaming sometimes those issues occurred as well. But if you disable the series renaming and enable the complete download handling, everything is working ok, and the episode file name is renamed as the release. No issues found for the last two years with this. Maybe you can compare the functionality on complete download handling in order to fix this.
But for the moment it's a bug as there is no possibility to have the file name renamed with the release name :)

Thanks!

**Comment by galli-leo** [comment]
@onedr0p @shocker2 It should already be working. The problem is if you are using a download client which does not give us the release name.

**Comment by shocker2** [comment]
I'm using the same client as Sonarr, NZBGet v17.1
Can I help with something in order to replicate?

**Comment by onedr0p** [comment]
I think he means, while the movie is downloading the name shows up as `534sdfjkasdklf45423434`

**Comment by shocker2** [comment]
Well, usually on NZB the download is spitted into archives. After the NZB extract the archives indeed it's showing as 5646353534535.mkv. Now when Radarr is importing this to the database and move the file into the location, it's not renaming it.
The same scenario is happening with Sonarr and it's working ok, with complete download handling enabled the file gets properly renamed with the release name.

Initially @galli-leo informed that I need to activate the movie rename functionality as with it disabled the complete download handling will do nothing.
Well, if you enable the movie rename functionality then the complete download handling will get bypassed.. it's confusing :)

This is what I'm getting in Sonarr:
Episode rename off, Complete Download Handling on -> Works ok, the 2354254543.mkv file gets renamed to the release name.
Episode rename on, CHD on -> same as Radarr, not working.
Episode rename on, CHD off -> same as Radarr, not working.

In Radarr
Not working in all the above scenarios.

**Comment by darzur** [comment]
It was reported in #393 and I can confirm it's still not working. Sonarr renames all my episodes, but Radarr not (with same settings).

**Comment by jojogrosso** [comment]
> The folder it's ok. The file is not getting renamed with the release name.
Also it will be nice to have a possibility to keep the folder name as the release name (as couchpotato is doing) as it's easier to identify what releases/versions you have.

The renamer renames the file name for me, but not the folder. I also would like to be able to keep the folder name as the release name (like CP) so you can identify what release you have.

**Comment by galli-leo** [comment]
@jojogrosso This is currently working on another branch. Will close this since another issue is already open for this feature.
