### ISSUE TITLE
Cannot add multiple imdb lists with different destination folders

### ISSUE THREAD

**Issue by RobKillilea** [Radarr/Radarr#679]
I have three lists I keep in imdb.com, one for kids movies, one for family movies to watch all together and one list for the grown-ups only. In my NAS I have three destination folders, this allows me to publish different sets of movies to different users in Plex, so the kids get one view and the adults another

When I add lists to Radarr I can choose what destination folder lists should add their movies to, **however this parameter is shared by all lists**. So if I define a list for adults and I set the folder to /media/adults and then define a list for kids and set the folder to /media/kids, when I go back to the first list that is now pointing to ../kids too

**Comment by onedr0p** [comment]
This is purely UI related? Do the movies get added to the right path?

**Comment by RobKillilea** [comment]
Not that I can see, when I go and look at the movies in the main screen afterwards they have the path from the list screen, i.e. it is carried on into the renaming process

So the R-rated horror movie pops up for the munchkins... :)

**Comment by RobKillilea** [comment]
i have also tested whether this is because I added the lists using the imdb preset option, it is not. All RSS lists that I create will share the same Folder setting

**Comment by onedr0p** [comment]
Okay will have a look into this.

**Comment by fremenfigure** [comment]
any progress? at this time I can't use multiple list to automatically add different types of movies, because everything goes to the same destination folder. Now I still need to manually modify the destination of each movie if it hasn't already been downloaded to the wrong folder.

**Comment by onedr0p** [comment]
Fixed in next release, let me know how it goes!

**Comment by RobKillilea** [comment]
Excellent, will test and report asap

**Comment by fremenfigure** [comment]
seems not fixed in Version 0.2.0.453.
Still changes target folder on all lists. and a new issue. when I check the movie the target folder is "C:\Services\Radarr\RadarrServer\<number>\" ??

**Comment by RobKillilea** [comment]
Agreed, issue not resolved and now new movies added pop up with the root of
the install rather than any of my movie folders - on linux for me
/opt/radarr/<number>/<MovieNameThe>

**Comment by galli-leo** [comment]
This is really just an UI issue, but I will take a look when I get time. Double check everytime you edit your list settings to set the correct path. It will not look changed, but it should save nonetheless. You can verify that by going into the db.

**Comment by RobKillilea** [comment]
As noted above, checking the paths for the lists when new movies are found
and added, shows a path with a new root, one based on the install folder
not the movie roots

It seems like the UI might be wrong, but the saved paths are not right
either

**Comment by galli-leo** [comment]
@RobKillilea With my local testing, it is definitely only in the UI. Still shouldn't happen though.

**Comment by RobKillilea** [comment]
So when you add a new movie to a list and sync with radarr, the movie pops
up as missing and monitored with the right folder and settings?

When I do that I get the format below.. /opt/radarr/<#>/<movienamethe>
My movie folder roots are all under /mnt/archive/....

**Comment by onedr0p** [comment]
@RobKillilea I understand your issue now, I'll take a look tomorrow afternoon and see if I can replicate your problem.

**Comment by onedr0p** [comment]
Moreover, I did just test adding a new list with a root folder, saved it, and imported a movie. The movie shows the right path and so does in the list settings. I have not tried adding a new movie to a existing list like a watch list. I'll try that tomorrow.

**Comment by MrLordy** [comment]
this seems too also be related too other lists like trakt. so i assume its also just UI related there also ?

**Comment by galli-leo** [comment]
@MrLordy correct.
